In [1]:
import numpy as np

In [2]:
# EXERCISE 8.1
# Create the following NumPy arrays:
# (a) float from 0.0 to 1.0 step 0.1, shape=(11,)
a = np.arange(0,1.1,0.1)
#a.shape --> (11,)

# (b) int zeros (1 byte) with shape=(5,6),
b = np.zeros(shape=(5,6), dtype=float)

# (c) complex with shape=(9,), powers of 1J. 
c = np.array( [complex(0, 1)**i for i in range(0, 9)], dtype=complex ) #przyjmuję 1J = 0 + ji 

In [3]:
print('8.1 a) \n',a,'\n')
print('8.1 b) \n',b,'\n')
print('8.1 c)',' \n',c,'\n')

8.1 a) 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 

8.1 b) 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

8.1 c)  
 [ 1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j] 



In [4]:
# EXERCISE 8.2
# (a) Create an arbitrary one dimensional array called v1.
v1 = np.arange(15)
# (b) Create a new array v2 which consists of the odd indices of v1.
v2 = v1[1::2] #zwraca co drugi indeks z v1 od indeksu 1 -> 3 -> 5 -> ...
# (c) Create a new array v3 in backwards ordering from v1.
v3 = v1[::-1]

In [5]:
print('v1 = ', v1)
print('v2 = ', v2)
print('v3 = ', v3)

v1 =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
v2 =  [ 1  3  5  7  9 11 13]
v3 =  [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [6]:
# EXERCISE 8.3
# (a) Create a two dimensional array called m1, shape=(4,5).
m1 = np.arange(20).reshape(4, 5)
# (b) Create a new array m2 from m1, in which the elements of each row are in reverse order.
m2 = np.flip(m1,1)
# (c) Create a new array m3 from m1, in which the elements of each column are in reverse order.
m3 = m1[::-1]
# (d) Cut of the first and last row and the first and last column of m1.
m4 = m1[1:-1,1:-1]
#lub:
# m4 = m1[1:3,1:4]

In [7]:
print('8.3 a) \n',m1)
print('8.3 b) \n',m2)
print('8.3 c) \n',m3)
print('8.3 d) \n',m4)

8.3 a) 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
8.3 b) 
 [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
8.3 c) 
 [[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
8.3 d) 
 [[ 6  7  8]
 [11 12 13]]
